package com.aura.attendix;

import android.content.SharedPreferences;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import com.android.volley.DefaultRetryPolicy;
import com.android.volley.AuthFailureError;
import com.android.volley.DefaultRetryPolicy;
import com.android.volley.Request;
import com.android.volley.DefaultRetryPolicy;
import com.android.volley.toolbox.JsonObjectRequest;
import com.android.volley.DefaultRetryPolicy;
import com.android.volley.toolbox.Volley;
import com.google.zxing.BarcodeFormat;
import com.journeyapps.barcodescanner.BarcodeEncoder;

import java.util.HashMap;
import java.util.Map;

/**
 * VirtualIdActivity — Student's living ID card.
 * Shows a QR code that refreshes every 12 seconds.
 * The QR encodes a cryptographically-signed timestamp token
 * generated by the backend. The Security Officer scans this.
 */
public class VirtualIdActivity extends AppCompatActivity {

    private ImageView ivQrCode;
    private TextView tvStudentName, tvRollNo, tvExpiry;

    private Handler refreshHandler = new Handler(Looper.getMainLooper());
    private static final int REFRESH_INTERVAL_MS = 12_000; // 12 seconds
    private String token = null;

    private final Runnable refreshRunnable = new Runnable() {
        @Override
        public void run() {
            fetchNewToken();
            refreshHandler.postDelayed(this, REFRESH_INTERVAL_MS);
        }
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_virtual_id);

        ivQrCode     = findViewById(R.id.ivQrCode);
        tvStudentName = findViewById(R.id.tvStudentName);
        tvRollNo     = findViewById(R.id.tvRollNo);
        tvExpiry     = findViewById(R.id.tvExpiry);

        findViewById(R.id.ivBack).setOnClickListener(v -> finish());

        SharedPreferences prefs = getSharedPreferences("UserSession", MODE_PRIVATE);
        tvStudentName.setText(prefs.getString("name", "Student"));
        tvRollNo.setText("Roll No: " + prefs.getString("username", "--"));

        fetchNewToken();
        refreshHandler.postDelayed(refreshRunnable, REFRESH_INTERVAL_MS);
    }

    private void fetchNewToken() {
        String authToken = getSharedPreferences("UserSession", MODE_PRIVATE)
                .getString("access_token", "");

        JsonObjectRequest request = new JsonObjectRequest(
                Request.Method.GET,
                NetworkConfig.URL_QR_TOKEN,
                null,
                response -> {
                    token = response.optString("token", "");
                    int expiresIn = response.optInt("expires_in_seconds", 15);
                    generateQrBitmap(token);
                    tvExpiry.setText("Refreshes every " + expiresIn + "s • Live Code");
                },
                error -> {
                    tvExpiry.setText("Connection error — retrying…");
                    Toast.makeText(this, "Could not refresh QR code", Toast.LENGTH_SHORT).show();
                }
        ) {
            @Override
            public Map<String, String> getHeaders() throws AuthFailureError {
                Map<String, String> headers = new HashMap<>();
                headers.put("Authorization", "Bearer " + authToken);
                return headers;
            }
        };

        request.setRetryPolicy(new DefaultRetryPolicy(6000, 0, 1.0f));
        VolleySingleton.getInstance(this).add(request);
    }

    private void generateQrBitmap(String content) {
        try {
            BarcodeEncoder encoder = new BarcodeEncoder();
            Bitmap bitmap = encoder.encodeBitmap(content, BarcodeFormat.QR_CODE, 600, 600);
            ivQrCode.setImageBitmap(bitmap);
        } catch (Exception e) {
            Toast.makeText(this, "QR generation error", Toast.LENGTH_SHORT).show();
        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        refreshHandler.removeCallbacks(refreshRunnable);
    }
}
