# Generated by Django 4.2.27 on 2026-01-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_fingerprint',
            field=models.CharField(blank=True, help_text="Unique Android ID of the student's registered device.", max_length=255, null=True),
        ),
    ]
