# Generated by Django 6.0.2 on 2026-03-26 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_address_user_blood_group_user_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='teacher_guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_cohort', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ACADEMIC_COORDINATOR', 'Academic Coordinator'), ('HOD', 'Head of Department'), ('TEACHER', 'Teacher'), ('TEACHER_GUARDIAN', 'Teacher Guardian'), ('SECURITY_OFFICER', 'Security Officer'), ('LIBRARIAN', 'Librarian'), ('FINANCE_CLERK', 'Finance Clerk'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('ADMIN', 'Admin')], default='STUDENT', max_length=25),
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.ManyToManyField(related_name='parents', to='core.studentprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
