# Generated by Django 6.0.2 on 2026-03-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_credits_user_fcm_device_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text="Unique Android ID of the student's registered device.", max_length=255, null=True),
        ),
    ]
